### PR TITLE
Add support to JupyterLab 2

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by jasongrout** [comment]
This PR looks right. Did you test it by generating a plugin and seeing if it works in jlab 1 and 2?

**Comment by martinRenou** [comment]
I did not but I should have, the build seems to fail with
```
src/plugin.ts(29,3): error TS2322: Type 'Token<IJupyterWidgetRegistry>[]' is not assignable to type 'Token<any>[]'.
      Type 'Token<IJupyterWidgetRegistry>' is not assignable to type 'Token<any>'.
        Types have separate declarations of a private property '_tokenStructuralPropertyT'.
```
Not sure I get the error I am not familiar with this Token system in JLab

**Comment by jasongrout** [comment]
Is this the jlab build when installing the plugin? For jlab 1 or jlab 2?

**Comment by martinRenou** [comment]
I seem to reproduce this error locally with JupyterLab `1.2.6` and JupyterLab `2.0.0`

**Comment by vidartf** [comment]
This is because the plugin is strongly typed:

https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/f41a76634ec7c197549d63aa454ccf001df502a1/%7B%7Bcookiecutter.github_project_name%7D%7D/src/plugin.ts#L27

Ref https://github.com/jupyter-widgets/ipywidgets/issues/2798#issuecomment-592531036

**Comment by jasongrout** [comment]
@martinRenou - can you check out the last few commits I added to this PR? I think it works now in jlab 2.

**Comment by martinRenou** [comment]
I pushed a commit but it is still failing.

I feel like it has to do with Karma not understanding ES6.

**Comment by vidartf** [comment]
@martinRenou It should work with this code (might need to adjust some paths) https://github.com/vidartf/opinionated-widget-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/ts/tests/karma.conf.js

**Comment by vidartf** [comment]
Ah, and with these: https://github.com/vidartf/opinionated-widget-cookiecutter/blob/b94f8a16c55a5f0014b2cfe41a0d0836b0fa469f/%7B%7Bcookiecutter.github_project_name%7D%7D/ts/package.json#L70-L71

**Pull request merged**
